[package]
name = "syncthingers"
version = "0.1.0"
edition = "2024"
authors = ["Asko Eronen"]
description = "A system tray application for managing Syncthing"

[dependencies]
tray-item = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opener = "0.7"
thiserror = "2.0"
log = "0.4"
simplelog = "0.12"
winapi = { version = "0.3", features = ["winuser", "processthreadsapi", "handleapi"] }
dirs = "5.0"

[build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "syncthingers.exe"
LegalCopyright = "Copyright © 2025"
ProductName = "Syncthingers"
FileDescription = "Syncthing System Tray Manager"
