# Base64 encoded small ICO file for a stopped icon (red circle with X)
$stoppedIconBase64 = "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAMMOAADDDgAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wDAqqrQwKqq0MCoqND///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AMCamtD/AAD//wAA//8AAP/AiIjQ////AP///wD///8A////AP///wD///8A////AP///wD///8AwJaW0P8AAP//AAD//wAA//8AAP//AAD/wICA0P///wD///8A////AP///wD///8A////AP///wDAgIDQ/wAA//8AAP//AAD//wAA//8AAP/AiIjQ/wAA/8B4eND///8A////AP///wD///8A////AMBwcND/AAD//wAA/8CQkND///8AwIiI0P8AAP//AAD//wAA/8BwcND///8A////AP///wD///8AwGho0P8AAP//AAD/wIiI0P///wD///8AwICA0P8AAP//AAD//wAA/8BgYND///8A////AP///wDAaGjQ/wAA//8AAP/AgIDQ////AP///wD///8AwICA0P8AAP//AAD//wAA/8BgYND///8A////AMBgYND/AAD//wAA/8CAgND///8A////AP///wD///8AwHh40P8AAP//AAD//wAA/8BYWND///8AwFhY0P8AAP//AAD/wHh40P///wD///8A////AP///wD///8AwHBw0P8AAP//AAD//wAA/8BYWNDA/wAA//8AAP/AcHDQ////AP///wD///8A////AP///wD///8A////AMBwcND/AAD//wAA//8AAP//AAD//wAA/8BoaND///8A////AP///wD///8A////AP///wD///8A////AP///wDAcHDQ/wAA//8AAP//AAD/wGBg0P///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AMBoaND/wICA0P///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

# Base64 encoded small ICO file for a running icon (green circle with checkmark)
$runningIconBase64 = "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAMMOAADDDgAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wDAqqrQwKqq0MCoqND///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AMCamtD/AAD//wAA//8AAP/AiIjQ////AP///wD///8A////AP///wD///8A////AP///wD///8AwJaW0P8AAP//AAD//wAA//8AAP//AAD/wICA0P///wD///8A////AP///wD///8A////AP///wDAgIDQ/wAA//8AAP//AAD//wAA//8AAP/AiIjQ/wAA/8B4eND///8A////AP///wD///8A////AMBwcND/wP////8AAP//AAD//wAA//8AAP//AAD//wAA/8BwcND///8A////AP///wD///8AwGho0P/A/////8D/////wP////8AAP//AAD//wAA//8AAP//AAD/wGBg0P///wD///8A////AMBoaND/wP////8AAP//AAD//8D/////wP////8AAP//AAD//wAA//8AAP/AYGDQ////AP///wDAYGDQ/8D/////AAD//wAA//8AAP//AAD//8D/////wP////8AAP//AAD//wAA/8BYWNDA////AMD//////////8D/////AAD//wAA//8AAP//AAD//wAA//8AAP//wP////8AAP//AAD//wAA////AAD//wAA//8AAP//wP////8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA/////wD///8A////AP///wD///8AwP////8AAP//AAD//wAA//8AAP//AAD//wAA/8BoaND///8A////AP///wD///8A////AP///wD///8A////AMBwcND/AAD//wAA//8AAP/AYGDQ////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8AwGho0P/AgIDQ////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

# Base64 encoded small ICO file for an app icon (blue circle with three lines)
$appIconBase64 = "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAMMOAADDDgAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wDMqoDQzKqA0Myqf9D///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AMyXZ9D3UiL/91Ih//dSIf/MkF/Q////AP///wD///8A////AP///wD///8A////AP///wD///8AzJVk0PdSIv/3UiH/91Ih//dSIf/3UiH/zIpY0P///wD///8A////AP///wD///8A////AP///wDMhVPQ91Ii//dSIf/MkF/Q91Ii//dSIf/MilnQ91Ih/8yAT9D///8A////AP///wD///8A////AMyAS9D3UiL/91Ih/8yPXtD///8AzIpY0PdSIv/3UiH/91Ih/8x6R9D///8A////AP///wD///8AzHlG0PdSIv/3UiH/zIpY0P///wD///8AzIVT0PdSIv/3UiH/91Ih/8x0Q9D///8A////AP///wDMeUbQ91Ii//dSIf/MhVPQ////AP///wD///8AzIVT0PdSIv/3UiH/91Ih/8x0Q9D///8A////AMx0QdD3UiL/91Ih/8yFU9D///8A////AP///wD///8AzH9N0PdSIv/3UiH/91Ih/8xuPdD///8AzG890PdSIv/3UiH/zH9O0P///wD///8A////AP///wD///8AzHlG0PdSIv/3UiH/91Ih/8xuPdDM91Ii//dSIf/MeUbQ////AP///wD///8A////AP///wD///8A////AMx5RtD3UiL/91Ih//dSIf/3UiH/91Ih/8xyQdD///8A////AP///wD///8A////AP///wD///8A////AP///wDMeUbQ91Ii//dSIf/3UiH/zHJA0P///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AMxzQdD/zIBQ0P///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

# Write the base64-encoded data to files
$stoppedIconBytes = [Convert]::FromBase64String($stoppedIconBase64)
[System.IO.File]::WriteAllBytes("resources\icons\syncthing_stopped.ico", $stoppedIconBytes)
Write-Host "Created stopped icon"

$runningIconBytes = [Convert]::FromBase64String($runningIconBase64)
[System.IO.File]::WriteAllBytes("resources\icons\syncthing_running.ico", $runningIconBytes)
Write-Host "Created running icon"

$appIconBytes = [Convert]::FromBase64String($appIconBase64)
[System.IO.File]::WriteAllBytes("resources\icons\syncthingers.ico", $appIconBytes)
Write-Host "Created app icon"

Write-Host "All icons created successfully!" 